#!/bin/bash

[[ -z "$TESTLIB_PATH" ]] && TESTLIB_PATH="/root/sut/lib"

echo path $TESTLIB_PATH

CTLIB_RUN_CMD=false

[[ -n "$TESTLIB" ]] || CTLIB_RUN_CMD=true

TESTLIB=1

. ${TESTLIB_PATH}/core.sh
. ${TESTLIB_PATH}/image.sh


[[ -e "~/.testconfig" ]] && . ~/.testconfig

# Only run main if this is not being included as a library
if $CTLIB_RUN_CMD ; then
    main "$@"
fi
