#!/bin/bash

# To use this library, include the following line:
[[ -z "$TESTLIB_PATH" ]] && TESTLIB_PATH="/root/sut/lib"

# Then as many as the sub-libraries as you need
. ${TESTLIB_PATH}/core.sh
. ${TESTLIB_PATH}/image.sh

# Include your defaults
[[ -e "~/.testconfig" ]] && . ~/.testconfig

# And do your own thing rather than running commands
# I suggest defining a "main" function of your own and running it like this.
cmdline "$@"
